name: "Continuous Integration"

on: push

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 8.15.6

      - name: Install dependencies
        run: pnpm install

      - name: Run Typescript
        run: npx tsc

      - name: Run Eslint
        run: npx eslint .